[project]
name = "groundless_veryl_cores"
version = "0.5.1"
authors = ["Akiyuki Okayasu"]
description = "A collection of cores for Groundless, written in Veryl."
license = "MIT or Apache-2.0"
repository = "https://github.com/AkiyukiOkayasu/groundless_veryl_cores"

[build]
sources = ["src"]
target = { type = "directory", path = "target" }

[test]

[dependencies]
# `AkiyukiOkayasu/gndless-fixedpoint-veryl`へ分離後は次のGit依存へ置き換える。
# fixedpoint = { project = "gndless_fixedpoint", github = "AkiyukiOkayasu/gndless-fixedpoint-veryl", version = "0.1.0" }
fixedpoint = { path = "./packages/fixedpoint" }
