[project]
name = "groundless_veryl_cores"
version = "0.1.0"
authors = ["Akiyuki Okayasu"]
description = "A collection of cores for Groundless, written in Veryl."
license = "MIT or Apache-2.0"
repository = "https://github.com/AkiyukiOkayasu/groundless_veryl_cores"

[build]
sources = ["src"]
target = { type = "directory", path = "target" }

[test]
simulator = "verilator"
waveform_format = "fst"

[test.verilator]
compile_args = ["-Wno-fatal"]

[lint.naming]
prefix_port_input = "i"
prefix_port_output = "o"
