[project]
name = "groundless_veryl_cores"
version = "0.5.1"
authors = ["Akiyuki Okayasu"]
description = "A collection of cores for Groundless, written in Veryl."
license = "MIT or Apache-2.0"
repository = "https://github.com/AkiyukiOkayasu/groundless_veryl_cores"

[build]
sources = ["src"]
target = { type = "directory", path = "target" }

[test]

[dependencies]
fixedpoint = { path = "./packages/fixedpoint" }
interpolation = { path = "./packages/interpolation" }
nco = { path = "./packages/nco" }
filter = { path = "./packages/filter" }
oscillator = { path = "./packages/oscillator" }
sample_rate_conversion = { path = "./packages/sample_rate_conversion" }
delta_sigma = { path = "./packages/delta_sigma" }
uart = { path = "./packages/uart" }
midi = { path = "./packages/midi" }
spi = { path = "./packages/spi" }
adat = { path = "./packages/adat" }
iec60958 = { path = "./packages/iec60958" }
