[project]
name = "gndless_spi"
version = "0.1.0"
authors = ["Akiyuki Okayasu"]
description = "Mode-configurable SPI master for Veryl."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AkiyukiOkayasu/gndless-spi-veryl"

[build]
sources = ["src"]
target = { type = "directory", path = "target" }

[test]
