[project]
name = "gndless_sample_rate_conversion"
version = "0.1.0"
authors = ["Akiyuki Okayasu"]
description = "Synchronous and asynchronous sample-rate converters for Veryl."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AkiyukiOkayasu/gndless-sample-rate-conversion-veryl"

[build]
sources = ["src"]
target = { type = "directory", path = "target" }

[test]

[dependencies]
fixedpoint = { path = "../fixedpoint" }
interpolation = { path = "../interpolation" }
nco = { path = "../nco" }
filter = { path = "../filter" }
oscillator = { path = "../oscillator" }
